### ISSUE TITLE
Asset hierarchy visualization

### ISSUE THREAD

**Issue by jaketbouma** [cognitedata/cognite-sdk-python#216] opened 2019-01-28 13:50 UTC
## Feature idea: Visualize asset hierarchy

As a data scientist I want to visualize, in a notebook, the asset hierarchy graph in the near vicinity of a certain node

## Inspiration
- Dasks DAG diagrams http://docs.dask.org/en/latest/custom-graphs.html
- sklearn graph_viz for decision trees https://medium.com/@rnbrown/creating-and-visualizing-decision-trees-with-python-f8e8fa394176

## Open questions
- Does this belong here or in ML hosting? We want customers to be able to use this
- Can this extend into a toolset for evaluating asset hierarchies?

**Comment by jaketbouma** [comment] 2019-01-28 13:50
@NealBouwmanCognite @bradleywhitlock FYI

**Comment by jaketbouma** [comment] 2019-03-05 08:49
@romanmotsar did an MVP as part of his onboarding :)
https://github.com/cognitedata/open-industrial-data/tree/master/contributions/assets-hierarchy-visualization

**Comment by dragly** [comment] 2019-03-13 17:44
I think this is a great idea! I could not view the notebook in the contrib (could you make a screenshot @jaketbouma?), but I think even a simple Jupyter widget that looks like a regular file browser tree could make sense:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/220658/54301829-fe5ba600-45bf-11e9-9e7c-db8d1fc7d466.png">

**Comment by erlendvollset** [comment] 2019-04-11 06:59
I've implemented a simple stdout version of this in #320.  This combined with being able to set a min and Max depth filter when retrieving assets should give the desired behaviour. It will be released in v1. Will this do? @jaketbouma

**Comment by erlendvollset** [comment] 2019-04-15 13:51
Duplicate of #325.

**Closed by erlendvollset** 2019-04-15 13:51 UTC
Labels: duplicate, feature request
