### ISSUE TITLE
Typing error: Type of "list" is partially unknown

### ISSUE THREAD

**Issue by miladh** [cognitedata/cognite-sdk-python#1677] opened 2024-03-18 06:59 UTC
**System information (please complete the following information):**
 - OS: Ubuntu 
 - Python Version: 3.9.18
 - SDK Version: 7.28.2

**Describe the bug**
Versions after 7.28.0 (https://github.com/cognitedata/cognite-sdk-python/pull/1667) triggers the pyright error: `Type of "list" is partially unknown`, for e.g.:

```python 
client.assets.list(limit=-1) 
```

**Comment by adiltamboli12** [comment] 2024-03-18 07:08
hellow can you give us a preffered output such as screenshot of how output you want

**Comment by miladh** [comment] 2024-03-18 08:28
The preferred solution would be to not get the typing errors. Here is an example CI run from a renovate PR that bumped the SDK version in one of our repos,  where the type-checker failed:
https://ci.jenkins.cogheim.net/blue/organizations/jenkins/cognitedata-ci%2Fcog-ai/detail/PR-1649/10/pipeline 

By adding `# type: ignore[reportUnknownMemberType]` I was able to suppress  the error, see e.g. [this commit](https://github.com/cognitedata/cog-ai/pull/1649/commits/9b1b6cdb8e5c755e3cc9a4d5af1d26dbd754d0f4).

But I believe this is something that should be fixed in SDK

**Comment by haakonvt** [comment] 2024-03-18 13:49
I'm unable to reproduce with 3.8 and 3.9. After taking a look at the referenced repo, I don't see `pylint` being an explicit dependency so I'm not sure what version of `pylint` to test with (I looked at `pyproject.toml`, `.pre-commit-config.yaml` and the `Jenkinsfile`)

**Comment by miladh** [comment] 2024-03-18 14:00
> I'm unable to reproduce with 3.8 and 3.9. After taking a look at the referenced repo, I don't see `pylint` being an explicit dependency so I'm not sure what version of `pylint` to test with (I looked at `pyproject.toml`, `.pre-commit-config.yaml` and the `Jenkinsfile`)

We are using `pyright` as type checker

**Comment by haakonvt** [comment] 2024-03-18 15:39
@miladh oh, haha, I see 😅 I ran it using poetry:
```
poetry run pre-commit run py-lint --all-files
```
...but somehow it succeeds for me 🤔 Is main perhaps updated - ah of course. I checked out 085ae95a2ea3fcba75231eda683ba86dd150e903 and I get the same errors. I'll have a look tomorrow 👍

**Comment by haakonvt** [comment] 2024-03-20 15:01
@miladh ...I've found the cause after quite some trial and error 😅 Made a PR here: https://github.com/cognitedata/cognite-sdk-python/pull/1682. I'll ping you once it has been merged and a new release has been made.

**Comment by haakonvt** [comment] 2024-03-20 20:42
Released now! Took the liberty to make a PR as well 😄 https://github.com/cognitedata/cog-ai/pull/1709

**Closed by haakonvt** 2024-03-20 20:42 UTC
Labels: bug
