### ISSUE TITLE
Make new release after changes in API v1

### ISSUE THREAD

**Issue by HMEiding** [cognitedata/cognite-sdk-python#433] opened 2019-07-05 09:22 UTC

**Comment by erlendvollset** [comment] 2019-07-10 11:59
This issue would be a lot more useful if it described the breaking changes that had been made in the API, as well as the temporary solutions that have been put in place, i.e. which tests that were skipped.

**Comment by erlendvollset** [comment] 2019-07-10 12:00
And perhaps a duplicate of this https://github.com/cognitedata/cognite-sdk-python/issues/429 ?

**Closed** 2019-07-10 15:39 UTC
